### ISSUE TITLE
"internal server error" on update from 1.8.1 to 1.8.2

### ISSUE THREAD

**Issue by dreua** [humhub/updater#27]
### What steps will reproduce the problem?
- Go to "Update HumHub" -> Start Update -> Start

### What is the expected result?
Update works. Or at least a more meaningful error message.

### What do you get instead?

> Downloading update package
> 
> Extracting package files
> 
> Validating package
> 
> Error!
> 
> An internal server error occurred.

### Additional info

There is a second HumHub instance on the same server which updated without issues. I've used the updater previously without issues.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.1 (Community Edition)
| PHP version      |  7.2.24 |
| Operating system | CentOS 8 | 

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

```
Exception: Make sure all files are writable! 
(/var/www/[redacted]/html/protected/humhub/modules/file/actions/DownloadAction.php) in 
/var/www/[redacted]/html/protected/modules/updater/modules/packageinstaller/controllers/InstallController.php:58

Stack trace:
#0 [internal function]: humhub\modules\updater\modules\packageinstaller\controllers\InstallController->actionValidate()
#1 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('validate', Array)
#4 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('package-install...', Array) 
#5 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request)) 
#6 /var/www/[redacted]/html/index.php(25): yii\base\Application->run() 
#7 {main}
```

![Screenshot_20210503_093309](https://user-images.githubusercontent.com/15114715/116853935-23c02980-abf7-11eb-9d17-3e7a03b53550.png)

Edit: removed sensitive content

**Comment by dreua** [comment]
Quick workaround: Maybe just add a link to `/index.php?r=admin%2Flogging` in case of errors

**Comment by dreua** [comment]
OT: The causing issue was fixed by a simple `chown apache:apache DownloadAction.php`. I recreated this file as root therefore it had the wrong permissions. 

What I want to see fixed here is a more stream lined UX for admins with similar issues, therefore I'll leave this issue open.
